apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  #serviceAccountName: dev-team
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
